import {demo,validateBook,parseText,readingMinutes} from './book.js';
import {read,write} from './storage.js';
const $=id=>document.getElementById(id);
const load=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))??fallback;}catch{return fallback;}};
function save(key,value){try{localStorage.setItem(key,JSON.stringify(value));}catch{toast('Nie można zapisać postępu na tym urządzeniu.');}}
let book=demo,index=0,restoring=false,timer,toastTimer,renderVersion=0;
let prefs={size:20,leading:1.85,width:700,font:'serif',theme:'night',...load('bf-prefs',{})};
let state={}; const urls=[];
function toast(text){$('toast').textContent=text;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').textContent='',4000);}
function applyPrefs(){const root=document.documentElement;root.dataset.theme=['night','paper','sepia'].includes(prefs.theme)?prefs.theme:'night';root.style.setProperty('--size',`${Math.min(30,Math.max(16,Number(prefs.size)||20))}px`);root.style.setProperty('--leading',Math.min(2.2,Math.max(1.4,Number(prefs.leading)||1.85)));root.style.setProperty('--width',`${Math.min(900,Math.max(480,Number(prefs.width)||700))}px`);root.style.setProperty('--font',prefs.font==='sans'?'system-ui,sans-serif':"Georgia,'Times New Roman',serif");$('font-size').value=prefs.size;$('line-height').value=prefs.leading;$('column-width').value=prefs.width;$('font-family').value=prefs.font;$('font-value').value=`${prefs.size} px`;document.querySelectorAll('.themes button').forEach(b=>b.setAttribute('aria-pressed',b.dataset.theme===prefs.theme));save('bf-prefs',prefs);}
const fraction=()=>{const max=document.documentElement.scrollHeight-innerHeight;return max>0?Math.min(1,Math.max(0,scrollY/max)):1;};
function persist(){if(restoring)return;state.chapter=book.chapters[index].id;state.fraction=fraction();save(`bf-state:${book.id}`,state);updateProgress();}
function updateProgress(){const p=Math.round(fraction()*100);$('progress').value=p;$('percentage').textContent=`${p}%`;}
function button(text,action){const b=document.createElement('button');b.textContent=text;b.onclick=action;return b;}
function renderBookmarks(){const el=$('bookmarks');el.replaceChildren();if(!state.bookmarks?.length){const p=document.createElement('p');p.className='muted';p.textContent='Jeszcze żadnej. Zapisz fragment, do którego chcesz wrócić.';el.append(p);return;}state.bookmarks.forEach((mark,i)=>{const chapter=book.chapters.findIndex(c=>c.id===mark.chapter);if(chapter<0)return;const row=document.createElement('div');row.append(button(`${book.chapters[chapter].title} · ${Math.round(mark.fraction*100)}%`,()=>showChapter(chapter,mark.fraction)));const remove=button('×',()=>{state.bookmarks.splice(i,1);save(`bf-state:${book.id}`,state);renderBookmarks();});remove.setAttribute('aria-label','Usuń zakładkę');row.append(remove);el.append(row);});}
async function showChapter(next,position=0){
  if(next<0||next>=book.chapters.length)return;
  clearTimeout(timer);restoring=true;const version=++renderVersion;index=next;urls.splice(0).forEach(URL.revokeObjectURL);
  const c=book.chapters[index];$('chapter-label').textContent=`Rozdział ${index+1} / ${book.chapters.length}`;$('chapter-kicker').textContent=book.title;$('chapter-title').textContent=c.title;$('chapter-meta').textContent=c.meta;$('time').textContent=`${readingMinutes(c)} min czytania`;$('status-label').textContent=`${index+1} / ${book.chapters.length}`;$('prev').disabled=index===0;$('next').disabled=index===book.chapters.length-1;
  $('toc').replaceChildren();book.chapters.forEach((ch,i)=>{const b=button(ch.title,()=>{persist();showChapter(i);});if(i===index)b.setAttribute('aria-current','true');const small=document.createElement('small');small.textContent=`${readingMinutes(ch)} min`;b.append(small);$('toc').append(b);});
  const content=$('content');content.replaceChildren();const images=[];
  for(const block of c.blocks){if(block.type!=='image'){const p=document.createElement('p');p.textContent=block.text;if(block.type==='notice')p.className='notice';content.append(p);continue;}
    const fig=document.createElement('figure'),img=document.createElement('img');img.alt=block.alt;img.decoding='async';let src=block.src;
    try{const blob=await read(`image:${book.id}:${block.src.split('/').pop()}`);if(blob){src=URL.createObjectURL(blob);urls.push(src);}}catch{}
    if(version!==renderVersion)return;
    const ready=new Promise(resolve=>{img.onload=resolve;img.onerror=()=>{const box=document.createElement('div');box.className='missing-image';const label=document.createElement('p');label.textContent=`${block.alt || 'Ilustracja'} · ${block.src.split('/').pop()}`;box.append(label,button('Dodaj ilustracje',()=>$('images').click()));img.replaceWith(box);resolve();};});fig.append(img);img.src=src;images.push(ready);if(block.caption){const cap=document.createElement('figcaption');cap.textContent=block.caption;fig.append(cap);}content.append(fig);
  }
  $('sidebar').classList.remove('open');$('toc-toggle').setAttribute('aria-expanded','false');renderBookmarks();
  await Promise.race([Promise.all(images),new Promise(resolve=>setTimeout(resolve,2500))]);
  if(version!==renderVersion)return;
  requestAnimationFrame(()=>{scrollTo(0,Math.max(0,document.documentElement.scrollHeight-innerHeight)*Math.min(1,Math.max(0,Number(position)||0)));restoring=false;persist();});
}
async function openBook(value){book=validateBook(value);const saved=load(`bf-state:${book.id}`,{});state={chapter:saved.chapter,fraction:Number(saved.fraction)||0,bookmarks:Array.isArray(saved.bookmarks)?saved.bookmarks:[]};$('book-title').textContent=book.title;$('book-subtitle').textContent=book.subtitle;$('chapter-count').textContent=book.chapters.length;document.title=`${book.title} — BookForge`;await showChapter(Math.max(0,book.chapters.findIndex(c=>c.id===state.chapter)),state.fraction);}
$('import').onclick=()=>$('file').click();
$('file').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>20*1024*1024)throw new Error('Maksymalny rozmiar książki to 20 MB.');const text=await file.text();const value=file.name.toLowerCase().endsWith('.json')?validateBook(JSON.parse(text)):parseText(text,file.name.replace(/\.[^.]+$/,''));try{await write('book',value);}catch{toast('Książkę otwarto, ale nie udało się jej zapisać w przeglądarce.');}persist();await openBook(value);}catch(err){toast(err instanceof SyntaxError?'Nieprawidłowy plik JSON.':err.message);}finally{e.target.value='';}};
$('images').onchange=async e=>{try{for(const f of e.target.files){if(!/^image\/(png|jpeg|webp|gif)$/.test(f.type)||f.size>10*1024*1024)throw new Error('Wybierz PNG, JPG, WebP lub GIF do 10 MB.');await write(`image:${book.id}:${f.name}`,f);}const pos=fraction();await showChapter(index,pos);toast('Ilustracje zapisane na tym urządzeniu.');}catch(err){toast(err.message);}finally{e.target.value='';}};
$('prev').onclick=()=>{persist();showChapter(index-1);};$('next').onclick=()=>{persist();showChapter(index+1);};$('bookmark').onclick=()=>{state.bookmarks??=[];if(state.bookmarks.length>=100){toast('Limit: 100 zakładek na książkę.');return;}state.bookmarks.push({chapter:book.chapters[index].id,fraction:fraction()});persist();renderBookmarks();toast('Zapisano zakładkę.');};
$('toc-toggle').onclick=()=>{$('toc-toggle').setAttribute('aria-expanded',$('sidebar').classList.toggle('open'));};
$('settings-toggle').onclick=()=>{$('settings').showModal();$('settings-toggle').setAttribute('aria-expanded','true');};$('settings-close').onclick=()=>$('settings').close();$('settings').addEventListener('close',()=>$('settings-toggle').setAttribute('aria-expanded','false'));
for(const [id,key] of [['font-size','size'],['line-height','leading'],['column-width','width'],['font-family','font']])$(id).oninput=e=>{prefs[key]=key==='font'?e.target.value:Number(e.target.value);applyPrefs();};
document.querySelectorAll('.themes button').forEach(b=>b.onclick=()=>{prefs.theme=b.dataset.theme;applyPrefs();});
addEventListener('scroll',()=>{updateProgress();clearTimeout(timer);timer=setTimeout(persist,180);},{passive:true});addEventListener('pagehide',persist);addEventListener('keydown',e=>{if($('settings').open||/INPUT|SELECT|TEXTAREA|BUTTON/.test(e.target.tagName)||e.altKey||e.ctrlKey||e.metaKey)return;if(e.key==='ArrowRight'){e.preventDefault();persist();showChapter(index+1);}if(e.key==='ArrowLeft'){e.preventDefault();persist();showChapter(index-1);}if(e.key==='Escape'){$('sidebar').classList.remove('open');$('toc-toggle').setAttribute('aria-expanded','false');}});
applyPrefs();let initial=demo;try{const stored=await read('book');if(stored)initial=validateBook(stored);}catch{toast('Pamięć przeglądarki jest niedostępna. Możesz czytać bez zapisu książki.');}await openBook(initial);
